target: all

common:
  storage:
    backend: s3
    s3:
      endpoint: "${S3_ENDPOINT}"
      access_key_id: "${S3_KEY_ID}"
      secret_access_key: "${S3_ACCESS_KEY}"
      bucket_name: "${S3_BUCKET_NAME}"

overrides_exporter:
  ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946

ingester:
  ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946
    replication_factor: 1

distributor:
  ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946

query_scheduler:
  ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946

ruler:
  ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946

alertmanager:
  sharding_ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946
    replication_factor: 1

compactor:
  sharding_ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946

store_gateway:
  sharding_ring:
    instance_addr: "${GOSSIP_ADDR}"
    instance_port: 7946
    replication_factor: 1

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

server:
  log_level: info

limits:
  compactor_blocks_retention_period: 1y

memberlist:
  join_members:
    - dns+mimir-1.monitoring.koyeb:7946
    - dns+mimir-2.monitoring.koyeb:7946
    - dns+mimir-3.monitoring.koyeb:7946
  advertise_addr: "${GOSSIP_ADDR}"
